Create table student
(

LRN NUMERIC (15),
SURNAME VARCHAR(20),
FIRSTNAME VARCHAR(20),
MI VARCHAR(20),
BIRTHDAY VARCHAR(20)
);

INSERT INTO STUDENT VALUES (123456789, 'GATDULA', 'RHODA', 'C', 'JUNE 15, 2023');

UPDATE STUDENT
SET LRN = 125107100007,
SURNAME = 'CAJOTE',
FIRSTNAME = 'JERRY',
MI = 'B',
BIRTHDAY = 'JULY 19, 2004'
WHERE LRN = 123456789;

 alter table buttercup_cup_cajote drop column MI;
 
 alter table student drop column MI;
-- ALTER TABLE DROP COLUMN MI;

ALTER TABLE STUDENT 
ADD  address VARCHAR(100);

update STUDENT 
SET ADDRESS ='SITIO CARPIOHAN FIHA HOMES, SANTIAGO GENERAL TRIAS CAVITE'
WHERE LRN = 125107100007;

ALTER TABLE STUDENT rename to BUTTER_cup_CAJOTE;

SELECT * FROM STUDENT;


select* from butter_cup_cajote;

DROP TABLE STUDENT


-- drop table butter_cup_cajote
