Create table CAJOTE
(
P_ID NUMERIC(5),
P_BRAND VARCHAR(20),
P_QUANTITY VARCHAR(20),
P_LOCATION VARCHAR(20),
ITEM VARCHAR (20),
P_PRICE NUMERIC(10),
ORDER_DATE VARCHAR(20)
);

INSERT INTO CAJOTE (P_ID, P_BRAND, P_QUANTITY, P_LOCATION, ITEM, P_PRICE, ORDER_DATE)
VALUES (1, 'NIKE', 12, 'MANILA' , 'BAG', 20, 'JANUARY 25, 2015');
INSERT INTO CAJOTE (P_ID, P_BRAND, P_QUANTITY, P_LOCATION, ITEM, P_PRICE, ORDER_DATE)
VALUES (2, 'NIKE', 39,'MANILA', 'CLOTHES', 23, 'FEBRUARY 23, 2015');
INSERT INTO CAJOTE (P_ID, P_BRAND, P_QUANTITY, P_LOCATION, ITEM, P_PRICE, ORDER_DATE)
VALUES (3,'ADIDAS', 438, 'CAVITE', 'SHOES', 99, 'MARCH 12, 2016');
INSERT INTO CAJOTE (P_ID, P_BRAND, P_QUANTITY, P_LOCATION, ITEM, P_PRICE, ORDER_DATE)
VALUES (4, 'ADIDAS', 524, 'ZAMBOANGA', 'SHIRT' , 123, 'AUGUST 5, 2015');
INSERT INTO CAJOTE (P_ID, P_BRAND, P_QUANTITY, P_LOCATION, ITEM, P_PRICE, ORDER_DATE)
VALUES (5, 'BENCH', 19, 'DAVAO', 'JACKET', 48, 'JUNE 12, 2017');
INSERT INTO CAJOTE (P_ID, P_BRAND, P_QUANTITY, P_LOCATION, ITEM, P_PRICE, ORDER_DATE)
VALUES (6, 'BALENO', 201, 'CAGAYAN', 'SOCKS', 23, 'MAY 20, 2018');
INSERT INTO CAJOTE (P_ID, P_BRAND, P_QUANTITY, P_LOCATION, ITEM, P_PRICE, ORDER_DATE)
VALUES (7, 'PENSHOPPE', 111, 'SULU', 'POLO', 2, 'OCTOBER 2, 2017');
INSERT INTO CAJOTE (P_ID, P_BRAND, P_QUANTITY, P_LOCATION, ITEM, P_PRICE, ORDER_DATE)
VALUES (8, 'CHANNEL', 231, 'BATANGAS', 'DRESS', 12, 'NOVEMBER 6, 2011');
INSERT INTO CAJOTE (P_ID, P_BRAND, P_QUANTITY, P_LOCATION, ITEM, P_PRICE, ORDER_DATE)
VALUES (9, 'UNDER ARMOUR', 511, 'LEYTE', 'SLIPPER', 36, 'APRIL 26, 2015');
INSERT INTO CAJOTE (P_ID, P_BRAND, P_QUANTITY, P_LOCATION, ITEM, P_PRICE, ORDER_DATE)
VALUES (10, 'PRADA', 123, 'MANILA', 'BAG', 53, 'JULY 4, 2017');
INSERT INTO CAJOTE (P_ID, P_BRAND, P_QUANTITY, P_LOCATION, ITEM, P_PRICE, ORDER_DATE)
VALUES (11, 'CALVIN KLEIN ', 234, 'CAVITE', 'SHIRT', 67, 'SEPTEMBER 26, 2015'); 
INSERT INTO CAJOTE (P_ID, P_BRAND, P_QUANTITY, P_LOCATION, ITEM, P_PRICE, ORDER_DATE)
VALUES (12, 'NEW BALANCE', 299, 'LAGUNA', 'SHOES', 343, 'DECEMBER 23, 2017');
INSERT INTO CAJOTE (P_ID, P_BRAND, P_QUANTITY, P_LOCATION, ITEM, P_PRICE, ORDER_DATE)
VALUES (13, 'REEBOK', 213, 'CAMARINES SUR', 'SHOES', 434, 'JUNE 29, 1979');

SELECT * FROM CAJOTE;

