create table  person(

person_id decimal(4),
first_name varchar(30)not null,
Last_name varchar(30)not null
);

insert into person values (1, 'jerry', 'cajote');
insert into person values (2, 'leodeldert', 'alegado');
insert into person values (3, 'brixter', 'alonzo');

select * from person;
alter table person 
drop column person_id;

alter table person add column Lrn decimal(14);

alter table person add primary key(Last_name);

alter table person rename to person;

 
create table parts (

part_id decimal generated by 
default as identity,
part_name varchar(30),
lead_time decimal(2,0)not null,
costs decimal(9,2)not null,
status decimal(1,0)not null,
primary key (part_id)
);

select*from parts;

insert into parts values ( 'sed dectrum', 5.0, 20.2, 2.0);

update parts set costs = 500
where part_id= 0;